import { Router } from 'express';
import authRoutes from './auth';
import orgRoutes from './org';
import contactRoutes from './contacts';
import templateRoutes from './templates';
import campaignRoutes from './campaigns';
import inboxRoutes from './inbox';
import aiRoutes from './ai';
import leadRoutes from './leads';
import paymentRoutes from './payments';
import analyticsRoutes from './analytics';
import webhookRoutes from './webhooks';
import dealRoutes from './deals';
import followupRoutes from './followups';
import clientLoveRoutes from './client-love';
import growthRoutes from './growth';
import megaRoutes from './mega';
import bspRoutes from './bsp';
import adminRoutes from './admin';
import aiTemplatesRoutes from './ai-templates';
import testNumberRoutes from './test-number';

const router = Router();
router.use('/auth', authRoutes);
router.use('/org', orgRoutes);
router.use('/contacts', contactRoutes);
router.use('/templates', templateRoutes);
router.use('/campaigns', campaignRoutes);
router.use('/inbox', inboxRoutes);
router.use('/ai', aiRoutes);
router.use('/leads', leadRoutes);
router.use('/payments', paymentRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/webhooks', webhookRoutes);
router.use('/deals', dealRoutes);
router.use('/followups', followupRoutes);
router.use('/client-love', clientLoveRoutes);
router.use('/growth', growthRoutes);
router.use('/mega', megaRoutes);
router.use('/bsp', bspRoutes);
router.use('/admin', adminRoutes);
router.use('/ai-templates', aiTemplatesRoutes);
router.use('/test-number', testNumberRoutes);
export default router;
